### ISSUE TITLE
Nutrition Game (tracker)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-hungergames#269]
### What
- [ ] Add a correct/delete mode for existing values
  - [ ] Add a single value deletion button
  - [ ] Add a delete all values button
  - [ ] Allow to unselect the photo (in case that's not a nutrition photo)
  - [ ] Allow to filter
    - [ ] Nutri-Score mismatch
    - [ ] Missing fiber
    - [ ] Missing kJ energy
    - [ ] Baby milks
    - [ ] Mineral waters
### Screenshots
 ![image](https://user-images.githubusercontent.com/1689815/133087311-f2c7417b-27f6-47af-80f7-e858ad6a28d3.png)
### Part of
- #234
